# Generated by Django 3.2.12 on 2022-04-01 02:15

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Book',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('book_title', models.CharField(max_length=50)),
                ('author', models.CharField(max_length=50)),
                ('keyword1', models.CharField(max_length=50)),
                ('keyword2', models.CharField(max_length=50, null=True)),
                ('keyword3', models.CharField(max_length=50, null=True)),
                ('comment', models.CharField(max_length=140, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
