# Generated by Django 3.2.12 on 2022-03-25 12:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mybible_app', '0002_auto_20220319_1345'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='book_title',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='book',
            name='keyword1',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='book',
            name='keyword2',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='book',
            name='keyword3',
            field=models.CharField(max_length=50, null=True),
        ),
    ]
